name: CI

on:
  push:
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  payload-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential clang-18 lld-18 xxd yasm nasm

      - name: Install toolchain
        run: |
          wget https://github.com/ps5-payload-dev/pacbrew-repo/releases/download/v0.26.1/ps5-payload-dev.tar.gz
          sudo tar xf ps5-payload-dev.tar.gz -C /

      - name: Build Payload
        run: |
          export PS5_PAYLOAD_SDK=/opt/ps5-payload-sdk
          make

      - name: Upload Payload ELF
        uses: actions/upload-artifact@v4
        with:
          name: ps5-self-decrypter
          path: ./bin/ps5-self-decrypter.elf
          if-no-files-found: error

